/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq;


import com.csci.cloud.admin.jooq.tables.TApplication;
import com.csci.cloud.admin.jooq.tables.TApplicationKey;
import com.csci.cloud.admin.jooq.tables.TConfigServer;
import com.csci.cloud.admin.jooq.tables.TPermission;
import com.csci.cloud.admin.jooq.tables.TTenant;
import com.csci.cloud.admin.jooq.tables.TUser;
import com.csci.cloud.admin.jooq.tables.TUserCaptcha;
import com.csci.cloud.admin.jooq.tables.TUserGroup;
import com.csci.cloud.admin.jooq.tables.TUserRefreshToken;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditCloudConsole extends SchemaImpl {

    private static final long serialVersionUID = -1317042753;

    /**
     * The reference instance of <code>credit_cloud_console</code>
     */
    public static final CreditCloudConsole CREDIT_CLOUD_CONSOLE = new CreditCloudConsole();

    /**
     * The table <code>credit_cloud_console.t_application</code>.
     */
    public final TApplication T_APPLICATION = TApplication.T_APPLICATION;

    /**
     * The table <code>credit_cloud_console.t_application_key</code>.
     */
    public final TApplicationKey T_APPLICATION_KEY = TApplicationKey.T_APPLICATION_KEY;

    /**
     * The table <code>credit_cloud_console.t_config_server</code>.
     */
    public final TConfigServer T_CONFIG_SERVER = TConfigServer.T_CONFIG_SERVER;

    /**
     * The table <code>credit_cloud_console.t_permission</code>.
     */
    public final TPermission T_PERMISSION = TPermission.T_PERMISSION;

    /**
     * The table <code>credit_cloud_console.t_tenant</code>.
     */
    public final TTenant T_TENANT = TTenant.T_TENANT;

    /**
     * The table <code>credit_cloud_console.t_user</code>.
     */
    public final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>credit_cloud_console.t_user_captcha</code>.
     */
    public final TUserCaptcha T_USER_CAPTCHA = TUserCaptcha.T_USER_CAPTCHA;

    /**
     * The table <code>credit_cloud_console.t_user_group</code>.
     */
    public final TUserGroup T_USER_GROUP = TUserGroup.T_USER_GROUP;

    /**
     * The table <code>credit_cloud_console.t_user_refresh_token</code>.
     */
    public final TUserRefreshToken T_USER_REFRESH_TOKEN = TUserRefreshToken.T_USER_REFRESH_TOKEN;

    /**
     * No further instances allowed
     */
    private CreditCloudConsole() {
        super("credit_cloud_console", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TApplication.T_APPLICATION,
            TApplicationKey.T_APPLICATION_KEY,
            TConfigServer.T_CONFIG_SERVER,
            TPermission.T_PERMISSION,
            TTenant.T_TENANT,
            TUser.T_USER,
            TUserCaptcha.T_USER_CAPTCHA,
            TUserGroup.T_USER_GROUP,
            TUserRefreshToken.T_USER_REFRESH_TOKEN);
    }
}
