/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq;


import com.csci.cloud.admin.jooq.tables.TApplication;
import com.csci.cloud.admin.jooq.tables.TApplicationKey;
import com.csci.cloud.admin.jooq.tables.TConfigServer;
import com.csci.cloud.admin.jooq.tables.TPermission;
import com.csci.cloud.admin.jooq.tables.TTenant;
import com.csci.cloud.admin.jooq.tables.TUser;
import com.csci.cloud.admin.jooq.tables.TUserCaptcha;
import com.csci.cloud.admin.jooq.tables.TUserGroup;
import com.csci.cloud.admin.jooq.tables.TUserRefreshToken;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in credit_cloud_console
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>credit_cloud_console.t_application</code>.
     */
    public static final TApplication T_APPLICATION = TApplication.T_APPLICATION;

    /**
     * The table <code>credit_cloud_console.t_application_key</code>.
     */
    public static final TApplicationKey T_APPLICATION_KEY = TApplicationKey.T_APPLICATION_KEY;

    /**
     * The table <code>credit_cloud_console.t_config_server</code>.
     */
    public static final TConfigServer T_CONFIG_SERVER = TConfigServer.T_CONFIG_SERVER;

    /**
     * The table <code>credit_cloud_console.t_permission</code>.
     */
    public static final TPermission T_PERMISSION = TPermission.T_PERMISSION;

    /**
     * The table <code>credit_cloud_console.t_tenant</code>.
     */
    public static final TTenant T_TENANT = TTenant.T_TENANT;

    /**
     * The table <code>credit_cloud_console.t_user</code>.
     */
    public static final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>credit_cloud_console.t_user_captcha</code>.
     */
    public static final TUserCaptcha T_USER_CAPTCHA = TUserCaptcha.T_USER_CAPTCHA;

    /**
     * The table <code>credit_cloud_console.t_user_group</code>.
     */
    public static final TUserGroup T_USER_GROUP = TUserGroup.T_USER_GROUP;

    /**
     * The table <code>credit_cloud_console.t_user_refresh_token</code>.
     */
    public static final TUserRefreshToken T_USER_REFRESH_TOKEN = TUserRefreshToken.T_USER_REFRESH_TOKEN;
}
