/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.daos;


import com.csci.cloud.auth.server.jooq.tables.TConfigServer;
import com.csci.cloud.auth.server.jooq.tables.records.TConfigServerRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TConfigServerDao extends DAOImpl<TConfigServerRecord, com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer, Integer> {

    /**
     * Create a new TConfigServerDao without any configuration
     */
    public TConfigServerDao() {
        super(TConfigServer.T_CONFIG_SERVER, com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer.class);
    }

    /**
     * Create a new TConfigServerDao with an attached configuration
     */
    public TConfigServerDao(Configuration configuration) {
        super(TConfigServer.T_CONFIG_SERVER, com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchById(Integer... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer fetchOneById(Integer value) {
        return fetchOne(TConfigServer.T_CONFIG_SERVER.ID, value);
    }

    /**
     * Fetch records that have <code>tenant_id IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByTenantId(Integer... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.TENANT_ID, values);
    }

    /**
     * Fetch records that have <code>server_name IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByServerName(String... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.SERVER_NAME, values);
    }

    /**
     * Fetch records that have <code>server_type IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByServerType(Integer... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.SERVER_TYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByStatus(Integer... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByCreatedAt(Timestamp... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TConfigServer> fetchByUpdatedAt(Timestamp... values) {
        return fetch(TConfigServer.T_CONFIG_SERVER.UPDATED_AT, values);
    }
}
