/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.daos;


import com.csci.cloud.auth.server.jooq.tables.TUserGroup;
import com.csci.cloud.auth.server.jooq.tables.records.TUserGroupRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserGroupDao extends DAOImpl<TUserGroupRecord, com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup, Integer> {

    /**
     * Create a new TUserGroupDao without any configuration
     */
    public TUserGroupDao() {
        super(TUserGroup.T_USER_GROUP, com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup.class);
    }

    /**
     * Create a new TUserGroupDao with an attached configuration
     */
    public TUserGroupDao(Configuration configuration) {
        super(TUserGroup.T_USER_GROUP, com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup> fetchById(Integer... values) {
        return fetch(TUserGroup.T_USER_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup fetchOneById(Integer value) {
        return fetchOne(TUserGroup.T_USER_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup> fetchByType(Integer... values) {
        return fetch(TUserGroup.T_USER_GROUP.TYPE, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup> fetchByCreatedAt(Timestamp... values) {
        return fetch(TUserGroup.T_USER_GROUP.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserGroup> fetchByUpdatedAt(Timestamp... values) {
        return fetch(TUserGroup.T_USER_GROUP.UPDATED_AT, values);
    }
}
