/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.daos;


import com.csci.cloud.auth.server.jooq.tables.TUserRefreshToken;
import com.csci.cloud.auth.server.jooq.tables.records.TUserRefreshTokenRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRefreshTokenDao extends DAOImpl<TUserRefreshTokenRecord, com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken, String> {

    /**
     * Create a new TUserRefreshTokenDao without any configuration
     */
    public TUserRefreshTokenDao() {
        super(TUserRefreshToken.T_USER_REFRESH_TOKEN, com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken.class);
    }

    /**
     * Create a new TUserRefreshTokenDao with an attached configuration
     */
    public TUserRefreshTokenDao(Configuration configuration) {
        super(TUserRefreshToken.T_USER_REFRESH_TOKEN, com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken object) {
        return object.getToken();
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken> fetchByToken(String... values) {
        return fetch(TUserRefreshToken.T_USER_REFRESH_TOKEN.TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken fetchOneByToken(String value) {
        return fetchOne(TUserRefreshToken.T_USER_REFRESH_TOKEN.TOKEN, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken> fetchByUserId(Integer... values) {
        return fetch(TUserRefreshToken.T_USER_REFRESH_TOKEN.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken fetchOneByUserId(Integer value) {
        return fetchOne(TUserRefreshToken.T_USER_REFRESH_TOKEN.USER_ID, value);
    }

    /**
     * Fetch records that have <code>tenant_id IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken> fetchByTenantId(Integer... values) {
        return fetch(TUserRefreshToken.T_USER_REFRESH_TOKEN.TENANT_ID, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken> fetchByCreatedAt(Timestamp... values) {
        return fetch(TUserRefreshToken.T_USER_REFRESH_TOKEN.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>expired_at IN (values)</code>
     */
    public List<com.csci.cloud.auth.server.jooq.tables.pojos.TUserRefreshToken> fetchByExpiredAt(Timestamp... values) {
        return fetch(TUserRefreshToken.T_USER_REFRESH_TOKEN.EXPIRED_AT, values);
    }
}
