/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables;


import com.csci.cloud.admin.jooq.CreditCloudConsole;
import com.csci.cloud.admin.jooq.Indexes;
import com.csci.cloud.admin.jooq.Keys;
import com.csci.cloud.admin.jooq.tables.records.TApplicationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TApplication extends TableImpl<TApplicationRecord> {

    private static final long serialVersionUID = -801735589;

    /**
     * The reference instance of <code>credit_cloud_console.t_application</code>
     */
    public static final TApplication T_APPLICATION = new TApplication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TApplicationRecord> getRecordType() {
        return TApplicationRecord.class;
    }

    /**
     * The column <code>credit_cloud_console.t_application.id</code>. 应用id
     */
    public final TableField<TApplicationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "应用id");

    /**
     * The column <code>credit_cloud_console.t_application.name</code>. 应用名称
     */
    public final TableField<TApplicationRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "应用名称");

    /**
     * The column <code>credit_cloud_console.t_application.tenant_id</code>. 租户id
     */
    public final TableField<TApplicationRecord, Integer> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "租户id");

    /**
     * The column <code>credit_cloud_console.t_application.status</code>. 应用状态：0-正常，9-删除
     */
    public final TableField<TApplicationRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "应用状态：0-正常，9-删除");

    /**
     * The column <code>credit_cloud_console.t_application.create_at</code>. 创建时间
     */
    public final TableField<TApplicationRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>credit_cloud_console.t_application.update_at</code>. 更新时间
     */
    public final TableField<TApplicationRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>credit_cloud_console.t_application</code> table reference
     */
    public TApplication() {
        this(DSL.name("t_application"), null);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_application</code> table reference
     */
    public TApplication(String alias) {
        this(DSL.name(alias), T_APPLICATION);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_application</code> table reference
     */
    public TApplication(Name alias) {
        this(alias, T_APPLICATION);
    }

    private TApplication(Name alias, Table<TApplicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TApplication(Name alias, Table<TApplicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TApplication(Table<O> child, ForeignKey<O, TApplicationRecord> key) {
        super(child, key, T_APPLICATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CreditCloudConsole.CREDIT_CLOUD_CONSOLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_APPLICATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TApplicationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_APPLICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TApplicationRecord> getPrimaryKey() {
        return Keys.KEY_T_APPLICATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TApplicationRecord>> getKeys() {
        return Arrays.<UniqueKey<TApplicationRecord>>asList(Keys.KEY_T_APPLICATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplication as(String alias) {
        return new TApplication(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplication as(Name alias) {
        return new TApplication(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TApplication rename(String name) {
        return new TApplication(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TApplication rename(Name name) {
        return new TApplication(name, null);
    }
}
