/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables;


import com.csci.cloud.admin.jooq.CreditCloudConsole;
import com.csci.cloud.admin.jooq.Indexes;
import com.csci.cloud.admin.jooq.Keys;
import com.csci.cloud.admin.jooq.tables.records.TUserRefreshTokenRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRefreshToken extends TableImpl<TUserRefreshTokenRecord> {

    private static final long serialVersionUID = -24401057;

    /**
     * The reference instance of <code>credit_cloud_console.t_user_refresh_token</code>
     */
    public static final TUserRefreshToken T_USER_REFRESH_TOKEN = new TUserRefreshToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRefreshTokenRecord> getRecordType() {
        return TUserRefreshTokenRecord.class;
    }

    /**
     * The column <code>credit_cloud_console.t_user_refresh_token.token</code>. 令牌
     */
    public final TableField<TUserRefreshTokenRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "令牌");

    /**
     * The column <code>credit_cloud_console.t_user_refresh_token.user_id</code>. 用户id
     */
    public final TableField<TUserRefreshTokenRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户id");

    /**
     * The column <code>credit_cloud_console.t_user_refresh_token.tenant_id</code>. 租户id
     */
    public final TableField<TUserRefreshTokenRecord, Integer> TENANT_ID = createField("tenant_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "租户id");

    /**
     * The column <code>credit_cloud_console.t_user_refresh_token.created_at</code>. 创建时间
     */
    public final TableField<TUserRefreshTokenRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>credit_cloud_console.t_user_refresh_token.expired_at</code>. 失效时间
     */
    public final TableField<TUserRefreshTokenRecord, Timestamp> EXPIRED_AT = createField("expired_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "失效时间");

    /**
     * Create a <code>credit_cloud_console.t_user_refresh_token</code> table reference
     */
    public TUserRefreshToken() {
        this(DSL.name("t_user_refresh_token"), null);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_user_refresh_token</code> table reference
     */
    public TUserRefreshToken(String alias) {
        this(DSL.name(alias), T_USER_REFRESH_TOKEN);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_user_refresh_token</code> table reference
     */
    public TUserRefreshToken(Name alias) {
        this(alias, T_USER_REFRESH_TOKEN);
    }

    private TUserRefreshToken(Name alias, Table<TUserRefreshTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserRefreshToken(Name alias, Table<TUserRefreshTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TUserRefreshToken(Table<O> child, ForeignKey<O, TUserRefreshTokenRecord> key) {
        super(child, key, T_USER_REFRESH_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CreditCloudConsole.CREDIT_CLOUD_CONSOLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_USER_REFRESH_TOKEN_PRIMARY, Indexes.T_USER_REFRESH_TOKEN_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserRefreshTokenRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_REFRESH_TOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserRefreshTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserRefreshTokenRecord>>asList(Keys.KEY_T_USER_REFRESH_TOKEN_PRIMARY, Keys.KEY_T_USER_REFRESH_TOKEN_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRefreshToken as(String alias) {
        return new TUserRefreshToken(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRefreshToken as(Name alias) {
        return new TUserRefreshToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRefreshToken rename(String name) {
        return new TUserRefreshToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRefreshToken rename(Name name) {
        return new TUserRefreshToken(name, null);
    }
}
