/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq;


import com.csci.cloud.auth.server.jooq.tables.TApplication;
import com.csci.cloud.auth.server.jooq.tables.TApplicationKey;
import com.csci.cloud.auth.server.jooq.tables.TConfigServer;
import com.csci.cloud.auth.server.jooq.tables.TPermission;
import com.csci.cloud.auth.server.jooq.tables.TTenant;
import com.csci.cloud.auth.server.jooq.tables.TUser;
import com.csci.cloud.auth.server.jooq.tables.TUserCaptcha;
import com.csci.cloud.auth.server.jooq.tables.TUserGroup;
import com.csci.cloud.auth.server.jooq.tables.TUserRefreshToken;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in credit_cloud_console
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>credit_cloud_console.t_application</code>.
     */
    public static final TApplication T_APPLICATION = com.csci.cloud.auth.server.jooq.tables.TApplication.T_APPLICATION;

    /**
     * The table <code>credit_cloud_console.t_application_key</code>.
     */
    public static final TApplicationKey T_APPLICATION_KEY = com.csci.cloud.auth.server.jooq.tables.TApplicationKey.T_APPLICATION_KEY;

    /**
     * The table <code>credit_cloud_console.t_config_server</code>.
     */
    public static final TConfigServer T_CONFIG_SERVER = com.csci.cloud.auth.server.jooq.tables.TConfigServer.T_CONFIG_SERVER;

    /**
     * The table <code>credit_cloud_console.t_permission</code>.
     */
    public static final TPermission T_PERMISSION = com.csci.cloud.auth.server.jooq.tables.TPermission.T_PERMISSION;

    /**
     * The table <code>credit_cloud_console.t_tenant</code>.
     */
    public static final TTenant T_TENANT = com.csci.cloud.auth.server.jooq.tables.TTenant.T_TENANT;

    /**
     * The table <code>credit_cloud_console.t_user</code>.
     */
    public static final TUser T_USER = com.csci.cloud.auth.server.jooq.tables.TUser.T_USER;

    /**
     * The table <code>credit_cloud_console.t_user_captcha</code>.
     */
    public static final TUserCaptcha T_USER_CAPTCHA = com.csci.cloud.auth.server.jooq.tables.TUserCaptcha.T_USER_CAPTCHA;

    /**
     * The table <code>credit_cloud_console.t_user_group</code>.
     */
    public static final TUserGroup T_USER_GROUP = com.csci.cloud.auth.server.jooq.tables.TUserGroup.T_USER_GROUP;

    /**
     * The table <code>credit_cloud_console.t_user_refresh_token</code>.
     */
    public static final TUserRefreshToken T_USER_REFRESH_TOKEN = com.csci.cloud.auth.server.jooq.tables.TUserRefreshToken.T_USER_REFRESH_TOKEN;
}
