/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.daos;


import com.csci.cloud.admin.jooq.tables.TApplicationKey;
import com.csci.cloud.admin.jooq.tables.records.TApplicationKeyRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TApplicationKeyDao extends DAOImpl<TApplicationKeyRecord, com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey, String> {

    /**
     * Create a new TApplicationKeyDao without any configuration
     */
    public TApplicationKeyDao() {
        super(TApplicationKey.T_APPLICATION_KEY, com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey.class);
    }

    /**
     * Create a new TApplicationKeyDao with an attached configuration
     */
    public TApplicationKeyDao(Configuration configuration) {
        super(TApplicationKey.T_APPLICATION_KEY, com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey object) {
        return object.getAppKey();
    }

    /**
     * Fetch records that have <code>app_key IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByAppKey(String... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.APP_KEY, values);
    }

    /**
     * Fetch a unique record that has <code>app_key = value</code>
     */
    public com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey fetchOneByAppKey(String value) {
        return fetchOne(TApplicationKey.T_APPLICATION_KEY.APP_KEY, value);
    }

    /**
     * Fetch records that have <code>app_secret IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByAppSecret(String... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.APP_SECRET, values);
    }

    /**
     * Fetch a unique record that has <code>app_secret = value</code>
     */
    public com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey fetchOneByAppSecret(String value) {
        return fetchOne(TApplicationKey.T_APPLICATION_KEY.APP_SECRET, value);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByAppId(Integer... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.APP_ID, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByStatus(Integer... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByCreateAt(Timestamp... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TApplicationKey> fetchByUpdateAt(Timestamp... values) {
        return fetch(TApplicationKey.T_APPLICATION_KEY.UPDATE_AT, values);
    }
}
