/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.daos;


import com.csci.cloud.admin.jooq.tables.TTenant;
import com.csci.cloud.admin.jooq.tables.records.TTenantRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTenantDao extends DAOImpl<TTenantRecord, com.csci.cloud.admin.jooq.tables.pojos.TTenant, Integer> {

    /**
     * Create a new TTenantDao without any configuration
     */
    public TTenantDao() {
        super(TTenant.T_TENANT, com.csci.cloud.admin.jooq.tables.pojos.TTenant.class);
    }

    /**
     * Create a new TTenantDao with an attached configuration
     */
    public TTenantDao(Configuration configuration) {
        super(TTenant.T_TENANT, com.csci.cloud.admin.jooq.tables.pojos.TTenant.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.csci.cloud.admin.jooq.tables.pojos.TTenant object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchById(Integer... values) {
        return fetch(TTenant.T_TENANT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.csci.cloud.admin.jooq.tables.pojos.TTenant fetchOneById(Integer value) {
        return fetchOne(TTenant.T_TENANT.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByName(String... values) {
        return fetch(TTenant.T_TENANT.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public com.csci.cloud.admin.jooq.tables.pojos.TTenant fetchOneByName(String value) {
        return fetchOne(TTenant.T_TENANT.NAME, value);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByCode(String... values) {
        return fetch(TTenant.T_TENANT.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>code = value</code>
     */
    public com.csci.cloud.admin.jooq.tables.pojos.TTenant fetchOneByCode(String value) {
        return fetchOne(TTenant.T_TENANT.CODE, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByType(Integer... values) {
        return fetch(TTenant.T_TENANT.TYPE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByStatus(Integer... values) {
        return fetch(TTenant.T_TENANT.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByCreatedAt(Timestamp... values) {
        return fetch(TTenant.T_TENANT.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<com.csci.cloud.admin.jooq.tables.pojos.TTenant> fetchByUpdateAt(Timestamp... values) {
        return fetch(TTenant.T_TENANT.UPDATE_AT, values);
    }
}
