/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TApplicationKey implements Serializable {

    private static final long serialVersionUID = -162020920;

    private String    appKey;
    private String    appSecret;
    private Integer   appId;
    private Integer   status;
    private Timestamp createAt;
    private Timestamp updateAt;

    public TApplicationKey() {}

    public TApplicationKey(TApplicationKey value) {
        this.appKey = value.appKey;
        this.appSecret = value.appSecret;
        this.appId = value.appId;
        this.status = value.status;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
    }

    public TApplicationKey(
        String    appKey,
        String    appSecret,
        Integer   appId,
        Integer   status,
        Timestamp createAt,
        Timestamp updateAt
    ) {
        this.appKey = appKey;
        this.appSecret = appSecret;
        this.appId = appId;
        this.status = status;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    public String getAppKey() {
        return this.appKey;
    }

    public TApplicationKey setAppKey(String appKey) {
        this.appKey = appKey;
        return this;
    }

    public String getAppSecret() {
        return this.appSecret;
    }

    public TApplicationKey setAppSecret(String appSecret) {
        this.appSecret = appSecret;
        return this;
    }

    public Integer getAppId() {
        return this.appId;
    }

    public TApplicationKey setAppId(Integer appId) {
        this.appId = appId;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public TApplicationKey setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public TApplicationKey setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public TApplicationKey setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TApplicationKey (");

        sb.append(appKey);
        sb.append(", ").append(appSecret);
        sb.append(", ").append(appId);
        sb.append(", ").append(status);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
