/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TApplication implements Serializable {

    private static final long serialVersionUID = -2104046336;

    private Integer   id;
    private String    name;
    private Integer   tenantId;
    private Integer   status;
    private Timestamp createAt;
    private Timestamp updateAt;

    public TApplication() {}

    public TApplication(TApplication value) {
        this.id = value.id;
        this.name = value.name;
        this.tenantId = value.tenantId;
        this.status = value.status;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
    }

    public TApplication(
        Integer   id,
        String    name,
        Integer   tenantId,
        Integer   status,
        Timestamp createAt,
        Timestamp updateAt
    ) {
        this.id = id;
        this.name = name;
        this.tenantId = tenantId;
        this.status = status;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    public Integer getId() {
        return this.id;
    }

    public TApplication setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public TApplication setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public TApplication setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public TApplication setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public Timestamp getCreateAt() {
        return this.createAt;
    }

    public TApplication setCreateAt(Timestamp createAt) {
        this.createAt = createAt;
        return this;
    }

    public Timestamp getUpdateAt() {
        return this.updateAt;
    }

    public TApplication setUpdateAt(Timestamp updateAt) {
        this.updateAt = updateAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TApplication (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(status);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
