/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserGroup implements Serializable {

    private static final long serialVersionUID = 820450778;

    private Integer   id;
    private Integer   type;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public TUserGroup() {}

    public TUserGroup(TUserGroup value) {
        this.id = value.id;
        this.type = value.type;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public TUserGroup(
        Integer   id,
        Integer   type,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.type = type;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public TUserGroup setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getType() {
        return this.type;
    }

    public TUserGroup setType(Integer type) {
        this.type = type;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public TUserGroup setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public TUserGroup setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserGroup (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
