/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRefreshToken implements Serializable {

    private static final long serialVersionUID = -201696767;

    private String    token;
    private Integer   userId;
    private Integer   tenantId;
    private Timestamp createdAt;
    private Timestamp expiredAt;

    public TUserRefreshToken() {}

    public TUserRefreshToken(TUserRefreshToken value) {
        this.token = value.token;
        this.userId = value.userId;
        this.tenantId = value.tenantId;
        this.createdAt = value.createdAt;
        this.expiredAt = value.expiredAt;
    }

    public TUserRefreshToken(
        String    token,
        Integer   userId,
        Integer   tenantId,
        Timestamp createdAt,
        Timestamp expiredAt
    ) {
        this.token = token;
        this.userId = userId;
        this.tenantId = tenantId;
        this.createdAt = createdAt;
        this.expiredAt = expiredAt;
    }

    public String getToken() {
        return this.token;
    }

    public TUserRefreshToken setToken(String token) {
        this.token = token;
        return this;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public TUserRefreshToken setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public TUserRefreshToken setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public TUserRefreshToken setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getExpiredAt() {
        return this.expiredAt;
    }

    public TUserRefreshToken setExpiredAt(Timestamp expiredAt) {
        this.expiredAt = expiredAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserRefreshToken (");

        sb.append(token);
        sb.append(", ").append(userId);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expiredAt);

        sb.append(")");
        return sb.toString();
    }
}
