/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.admin.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = -1014463938;

    private Integer   id;
    private Integer   tenantId;
    private String    loginName;
    private String    password;
    private String    email;
    private String    mobile;
    private Integer   emailVerified;
    private Integer   mobileVerified;
    private Integer   status;
    private Integer   groupId;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.tenantId = value.tenantId;
        this.loginName = value.loginName;
        this.password = value.password;
        this.email = value.email;
        this.mobile = value.mobile;
        this.emailVerified = value.emailVerified;
        this.mobileVerified = value.mobileVerified;
        this.status = value.status;
        this.groupId = value.groupId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public TUser(
        Integer   id,
        Integer   tenantId,
        String    loginName,
        String    password,
        String    email,
        String    mobile,
        Integer   emailVerified,
        Integer   mobileVerified,
        Integer   status,
        Integer   groupId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.tenantId = tenantId;
        this.loginName = loginName;
        this.password = password;
        this.email = email;
        this.mobile = mobile;
        this.emailVerified = emailVerified;
        this.mobileVerified = mobileVerified;
        this.status = status;
        this.groupId = groupId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public TUser setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public TUser setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public TUser setLoginName(String loginName) {
        this.loginName = loginName;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public TUser setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public TUser setEmail(String email) {
        this.email = email;
        return this;
    }

    public String getMobile() {
        return this.mobile;
    }

    public TUser setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    public Integer getEmailVerified() {
        return this.emailVerified;
    }

    public TUser setEmailVerified(Integer emailVerified) {
        this.emailVerified = emailVerified;
        return this;
    }

    public Integer getMobileVerified() {
        return this.mobileVerified;
    }

    public TUser setMobileVerified(Integer mobileVerified) {
        this.mobileVerified = mobileVerified;
        return this;
    }

    public Integer getStatus() {
        return this.status;
    }

    public TUser setStatus(Integer status) {
        this.status = status;
        return this;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public TUser setGroupId(Integer groupId) {
        this.groupId = groupId;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public TUser setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public TUser setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(loginName);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(emailVerified);
        sb.append(", ").append(mobileVerified);
        sb.append(", ").append(status);
        sb.append(", ").append(groupId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
