/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.records;


import com.csci.cloud.auth.server.jooq.tables.TApplication;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TApplicationRecord extends UpdatableRecordImpl<TApplicationRecord> implements Record6<Integer, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 791660407;

    /**
     * Setter for <code>credit_cloud_console.t_application.id</code>. 应用id
     */
    public TApplicationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.id</code>. 应用id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>credit_cloud_console.t_application.name</code>. 应用名称
     */
    public TApplicationRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.name</code>. 应用名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>credit_cloud_console.t_application.tenant_id</code>. 租户id
     */
    public TApplicationRecord setTenantId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.tenant_id</code>. 租户id
     */
    public Integer getTenantId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>credit_cloud_console.t_application.status</code>. 应用状态：0-正常，9-删除
     */
    public TApplicationRecord setStatus(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.status</code>. 应用状态：0-正常，9-删除
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>credit_cloud_console.t_application.create_at</code>. 创建时间
     */
    public TApplicationRecord setCreateAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>credit_cloud_console.t_application.update_at</code>. 更新时间
     */
    public TApplicationRecord setUpdateAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_application.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TApplication.T_APPLICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TApplication.T_APPLICATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TApplication.T_APPLICATION.TENANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TApplication.T_APPLICATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TApplication.T_APPLICATION.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TApplication.T_APPLICATION.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTenantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTenantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value3(Integer value) {
        setTenantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord value6(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TApplicationRecord values(Integer value1, String value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TApplicationRecord
     */
    public TApplicationRecord() {
        super(TApplication.T_APPLICATION);
    }

    /**
     * Create a detached, initialised TApplicationRecord
     */
    public TApplicationRecord(Integer id, String name, Integer tenantId, Integer status, Timestamp createAt, Timestamp updateAt) {
        super(TApplication.T_APPLICATION);

        set(0, id);
        set(1, name);
        set(2, tenantId);
        set(3, status);
        set(4, createAt);
        set(5, updateAt);
    }
}
