/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.records;


import com.csci.cloud.auth.server.jooq.tables.TConfigServer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TConfigServerRecord extends UpdatableRecordImpl<TConfigServerRecord> implements Record7<Integer, Integer, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 745110834;

    /**
     * Setter for <code>credit_cloud_console.t_config_server.id</code>. 用户组id
     */
    public TConfigServerRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.id</code>. 用户组id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.tenant_id</code>. 用户id
     */
    public TConfigServerRecord setTenantId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.tenant_id</code>. 用户id
     */
    public Integer getTenantId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.server_name</code>. 服务名称
     */
    public TConfigServerRecord setServerName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.server_name</code>. 服务名称
     */
    public String getServerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.server_type</code>. 服务类型 0: 区块链 1:企业征信 2:个人征信
     */
    public TConfigServerRecord setServerType(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.server_type</code>. 服务类型 0: 区块链 1:企业征信 2:个人征信
     */
    public Integer getServerType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.status</code>. 服务状态.0:开启 1：关闭
     */
    public TConfigServerRecord setStatus(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.status</code>. 服务状态.0:开启 1：关闭
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.created_at</code>. 创建时间
     */
    public TConfigServerRecord setCreatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>credit_cloud_console.t_config_server.updated_at</code>. 更新时间
     */
    public TConfigServerRecord setUpdatedAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_config_server.updated_at</code>. 更新时间
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TConfigServer.T_CONFIG_SERVER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TConfigServer.T_CONFIG_SERVER.TENANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TConfigServer.T_CONFIG_SERVER.SERVER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TConfigServer.T_CONFIG_SERVER.SERVER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TConfigServer.T_CONFIG_SERVER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TConfigServer.T_CONFIG_SERVER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TConfigServer.T_CONFIG_SERVER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTenantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getServerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getServerType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTenantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getServerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getServerType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value2(Integer value) {
        setTenantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value3(String value) {
        setServerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value4(Integer value) {
        setServerType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TConfigServerRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TConfigServerRecord
     */
    public TConfigServerRecord() {
        super(TConfigServer.T_CONFIG_SERVER);
    }

    /**
     * Create a detached, initialised TConfigServerRecord
     */
    public TConfigServerRecord(Integer id, Integer tenantId, String serverName, Integer serverType, Integer status, Timestamp createdAt, Timestamp updatedAt) {
        super(TConfigServer.T_CONFIG_SERVER);

        set(0, id);
        set(1, tenantId);
        set(2, serverName);
        set(3, serverType);
        set(4, status);
        set(5, createdAt);
        set(6, updatedAt);
    }
}
