/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.records;


import com.csci.cloud.auth.server.jooq.tables.TPermission;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPermissionRecord extends UpdatableRecordImpl<TPermissionRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1771646947;

    /**
     * Setter for <code>credit_cloud_console.t_permission.group_id</code>. 用户组id
     */
    public TPermissionRecord setGroupId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_permission.group_id</code>. 用户组id
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>credit_cloud_console.t_permission.permissions</code>. 权限，用半角逗号分隔(,)
     */
    public TPermissionRecord setPermissions(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>credit_cloud_console.t_permission.permissions</code>. 权限，用半角逗号分隔(,)
     */
    public String getPermissions() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TPermission.T_PERMISSION.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPermission.T_PERMISSION.PERMISSIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPermissions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPermissions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord value2(String value) {
        setPermissions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPermissionRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPermissionRecord
     */
    public TPermissionRecord() {
        super(TPermission.T_PERMISSION);
    }

    /**
     * Create a detached, initialised TPermissionRecord
     */
    public TPermissionRecord(Integer groupId, String permissions) {
        super(TPermission.T_PERMISSION);

        set(0, groupId);
        set(1, permissions);
    }
}
