/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables;


import com.csci.cloud.auth.server.jooq.CreditCloudConsole;
import com.csci.cloud.auth.server.jooq.Indexes;
import com.csci.cloud.auth.server.jooq.Keys;
import com.csci.cloud.auth.server.jooq.tables.records.TUserGroupRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserGroup extends TableImpl<TUserGroupRecord> {

    private static final long serialVersionUID = 390726464;

    /**
     * The reference instance of <code>credit_cloud_console.t_user_group</code>
     */
    public static final TUserGroup T_USER_GROUP = new TUserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserGroupRecord> getRecordType() {
        return TUserGroupRecord.class;
    }

    /**
     * The column <code>credit_cloud_console.t_user_group.id</code>. 用户组id
     */
    public final TableField<TUserGroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "用户组id");

    /**
     * The column <code>credit_cloud_console.t_user_group.type</code>. 用户组类型：0-普通管理员，1-非管理员，9-系统管理员
普通管理员有账户所有app、service、module的权限。
系统管理员有所有账户app、service、module的权限。
非管理员需要关联t_permission表查询权限。
     */
    public final TableField<TUserGroupRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "用户组类型：0-普通管理员，1-非管理员，9-系统管理员\n普通管理员有账户所有app、service、module的权限。\n系统管理员有所有账户app、service、module的权限。\n非管理员需要关联t_permission表查询权限。");

    /**
     * The column <code>credit_cloud_console.t_user_group.created_at</code>. 创建时间
     */
    public final TableField<TUserGroupRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>credit_cloud_console.t_user_group.updated_at</code>. 更新时间
     */
    public final TableField<TUserGroupRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>credit_cloud_console.t_user_group</code> table reference
     */
    public TUserGroup() {
        this(DSL.name("t_user_group"), null);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_user_group</code> table reference
     */
    public TUserGroup(String alias) {
        this(DSL.name(alias), T_USER_GROUP);
    }

    /**
     * Create an aliased <code>credit_cloud_console.t_user_group</code> table reference
     */
    public TUserGroup(Name alias) {
        this(alias, T_USER_GROUP);
    }

    private TUserGroup(Name alias, Table<TUserGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserGroup(Name alias, Table<TUserGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TUserGroup(Table<O> child, ForeignKey<O, TUserGroupRecord> key) {
        super(child, key, T_USER_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CreditCloudConsole.CREDIT_CLOUD_CONSOLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_USER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TUserGroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_USER_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserGroupRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserGroupRecord>>asList(Keys.KEY_T_USER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserGroup as(String alias) {
        return new TUserGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserGroup as(Name alias) {
        return new TUserGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserGroup rename(String name) {
        return new TUserGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserGroup rename(Name name) {
        return new TUserGroup(name, null);
    }
}
