/*
 * This file is generated by jOOQ.
 */
package com.csci.cloud.auth.server.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserCaptcha implements Serializable {

    private static final long serialVersionUID = -1769719094;

    private Integer   id;
    private String    loginName;
    private Integer   times;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public TUserCaptcha() {}

    public TUserCaptcha(TUserCaptcha value) {
        this.id = value.id;
        this.loginName = value.loginName;
        this.times = value.times;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public TUserCaptcha(
        Integer   id,
        String    loginName,
        Integer   times,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.loginName = loginName;
        this.times = times;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public TUserCaptcha setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public TUserCaptcha setLoginName(String loginName) {
        this.loginName = loginName;
        return this;
    }

    public Integer getTimes() {
        return this.times;
    }

    public TUserCaptcha setTimes(Integer times) {
        this.times = times;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public TUserCaptcha setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public TUserCaptcha setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserCaptcha (");

        sb.append(id);
        sb.append(", ").append(loginName);
        sb.append(", ").append(times);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
